view:
  path: ../app/view
  layout: layouts/page

db:
  host: localhost
  user: root
  pass: root
  database: hackathon-starter

api:
  send-mailer: mailgun

title: Hackathon Starter
apiconfig:
  email: true
