<div class="container">
	<div class="page-header">
		<h3>Profile Information</h3>
	</div>

	<div class="alert alert-success" role="alert" ng-show="message.profile">Profile successfully saved</div>
	<div class="alert alert-danger" role="alert" ng-show="message.profileError">{{message.profileError}}</div>

	<form class="form-horizontal">
		<div class="form-group">
			<label for="email" class="col-sm-2 control-label">Email</label>
			<div class="col-sm-4"><input type="email" name="email" id="email" class="form-control" ng-model="user.email"></div>
		</div>
		<div class="form-group">
			<label for="name" class="col-sm-2 control-label">Name</label>
			<div class="col-sm-4"><input type="text" name="name" id="name" class="form-control" ng-model="user.name"></div>
		</div>
		<div class="form-group">
			<label for="gender" class="col-sm-2 control-label">Gender</label>
			<div class="col-sm-4"><label class="radio col-sm-4"><input type="radio" checked name="gender" value="male" data-toggle="radio" ng-model="user.gender"><span>Male</span></label><label class="radio col-sm-4"><input type="radio" name="gender" value="female" data-toggle="radio" ng-model="user.gender"><span>Female</span></label></div>
		</div>
		<div class="form-group">
			<label for="location" class="col-sm-2 control-label">Location</label>
			<div class="col-sm-4"><input type="text" name="location" id="location" class="form-control" ng-model="user.location"></div>
		</div>
		<div class="form-group">
			<label for="website" class="col-sm-2 control-label">Website</label>
			<div class="col-sm-4"><input type="text" name="website" id="website" class="form-control" ng-model="user.website"></div>
		</div>
		<div class="form-group">
			<label for="gravatar" class="col-sm-2 control-label">Gravatar</label>
			<div class="col-sm-4"><img ng-src="{{user.image}}" width="100" height="100" class="profile"></div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-4"><button type="submit" class="btn btn btn-primary" ng-click="save()"><i class="fa fa-pencil"></i>Update Profile</button></div>
		</div>
	</form>


	<div class="page-header">
		<h3>{{user.auth.local ? 'Change' : 'Add a'}} Password</h3>
	</div>
	<div class="alert alert-success" role="alert" ng-show="message.password == 1">Password successfully saved</div>
	<div class="alert alert-danger" role="alert" ng-show="message.password == 2">Failed saving password</div>

	<div class="alert alert-info" role="alert" ng-show="!user.email">To login with a password, you must enter an <b>Email Address</b> above.</div>


	<form class="form-horizontal">
		<div class="form-group">
			<label for="password" class="col-sm-2 control-label">New Password</label>
			<div class="col-sm-4"><input type="password" name="password" id="password" class="form-control" ng-model="pass1"></div>
		</div>
		<div class="form-group">
			<label for="confirmPassword" class="col-sm-2 control-label">Confirm Password</label>
			<div class="col-sm-4"><input type="password" name="confirmPassword" id="confirmPassword" class="form-control" ng-model="pass2"></div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-4"><button type="submit" class="btn btn btn-primary" ng-click="passwd()"><i class="fa fa-lock"></i>{{user.auth.local ? 'Change' : 'Add a'}} Password</button></div>
		</div>
	</form>


	<div class="page-header">
		<h3>Delete Account</h3>
	</div>
	<p>You can delete your account, but keep in mind this action is irreversible.</p>
	<button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#deleteAccountConfirm"><i class="fa fa-trash"></i>Delete my account</button>


	<div class="page-header">
		<h3>Linked Accounts</h3>
	</div>
	<p>
		<a ng-show="user.auth.instagram" href="/account/unlink/instagram" class="text-danger">Unlink your Instagram account</a>
		<a ng-hide="user.auth.instagram" href="/auth/instagram" target="_top">Link your Instagram account</a>
	</p>
	<p>
		<a ng-show="user.auth.google" href="/account/unlink/google" class="text-danger">Unlink your Google account</a>
		<a ng-hide="user.auth.google" href="/auth/google" target="_top">Link your Google account</a>
	</p>
	<p>
		<a ng-show="user.auth.facebook" href="/account/unlink/facebook" class="text-danger">Unlink your Facebook account</a>
		<a ng-hide="user.auth.facebook" href="/auth/facebook" target="_top">Link your Facebook account</a>
	</p>
	<p>
		<a ng-show="user.auth.twitter" href="/account/unlink/twitter" class="text-danger">Unlink your Twitter account</a>
		<a ng-hide="user.auth.twitter" href="/auth/twitter" target="_top">Link your Twitter account</a>
	</p>
	<p>
		<a ng-show="user.auth.github" href="/account/unlink/github" class="text-danger">Unlink your GitHub account</a>
		<a ng-hide="user.auth.github" href="/auth/github" target="_top">Link your GitHub account</a>
	</p>
	<p>
		<a ng-show="user.auth.linkedin" href="/account/unlink/linkedin" class="text-danger">Unlink your Linkedin account</a>
		<a ng-hide="user.auth.linkedin" href="/auth/linkedin" target="_top">Link your Linkedin account</a>
	</p>
</div>


<div class="modal fade" id="deleteAccountConfirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="exampleModalLabel">Are you sure you want to delete your account?</h4>
			</div>

			<div class="modal-body">
				<div ng-show="user.email">
					<p>Please confirm you wish to delete your account and all data associated with it by entering your email below.</p>
					<form>
						<div class="form-group">
							<input type="text" class="form-control" id="confirm-delete-email" ng-model="confirmDeleteEmail" placeholder="Email">
						</div>
					</form>
				</div>
				<div ng-show="!user.email">
					<p>This action is irreversible.</p>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-link" data-dismiss="modal">Cancel</button>
				<button type="button" class="btn btn-default" ng-class="{'btn-success': !user.email || confirmDeleteEmail == user.email}" ng-click="delete()">Delete</button>
			</div>
		</div>
	</div>
</div>
