<div class="container">

	<div class="col-sm-8 col-sm-offset-2">
		<div class="page-header">
			<h3>Forgot Password</h3>
		</div>
		<div class="alert alert-danger" role="alert" ng-show="forgotError">Invalid email</div>
		<div class="alert alert-success" role="alert" ng-show="forgotComplete">Please check your email for instructions on how to reset your password</div>

		<form ng-submit="forgot()" ng-hide="forgotComplete">
			<div class="form-group">
				<p>Enter your email address below and we will send you password reset instructions.</p>
				<label for="email" class="control-label">Email</label><input type="email" name="email" id="email" placeholder="Email" autofocus class="form-control" ng-model="email">
			</div>
			<div class="form-group"><button type="submit" class="btn btn-primary"><i class="fa fa-key"></i>Reset Password</button></div>
		</form>
	</div>
</div>
