<div class="splash">
	<div class="container">

		<div class="row">
			<div class="col-lg-12">

				<div class="page-header">
					<h1>Hackathon Starter</h1>
				</div>
				<p class="lead">A boilerplate for PHP + AngularJS web applications.</p>

			</div>
		</div>

	</div>
</div>

<div class="container product-items">
	<div class="row">
		<div class="col-lg-4 col-sm-6">
			<h3><i class="fa fa-github"></i> Open Source</h3>
			<p>Hackathon Starter is released under the MIT License and maintained by the community of one person on <a target="_blank" href="https://github.com/arzynik/hackathon-starter">GitHub</a>.</p>
		</div>
		<div class="col-lg-4 col-sm-6">
			<h3><i class="fa fa-wrench"></i> Angular 1.5</h3>
			<p>Built with the latest <a href="https://angularjs.org/" target="_blank">AngularJS</a> 1.5 that is likly to be horibly unstable and break all the time. But who needs stability?</p>
		</div>
		<div class="col-lg-4 col-sm-6">
			<h3><i class="fa fa-cogs"></i> Tipsy 0.11</h3>
			<p>Use the lastest version of the new <a href="http://tipsy.la" target="_blank">Tipsy</a> PHP Framework and do lots of stuff awesome.</p>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-4 col-sm-6">
			<h3><i class="fa fa-cloud"></i> SASS</h3>
			<p>Leverage the awesome power of <a href="http://sass-lang.com/" target="_blank">SASS</a> to become a CSS super hero. Also annoy anyone who doesnt have sass easily available to them.</p>
		</div>
		<div class="col-lg-4 col-sm-6">
			<h3><i class="fa fa-database"></i> Doctrine</h3>
			<p>Use the popular <a href="http://www.doctrine-project.org/" target="_blank">Doctrine</a> ORM to easily create and manage sexy schema of either MySQL or PostgreSQL.</p>
		</div>
		<div class="col-lg-4 col-sm-6">
			<h3><i class="fa fa-cloud"></i> OAuth</h3>
			<p>Use Facebook, Twitter, GitHub, or many other OAuth enabled providers to allow your users to log in or sign up instantly.</p>
		</div>
	</div>
</div>
