

<div class="col-sm-8 col-sm-offset-2">
	<div class="page-header">
		<h3>Sign in</h3>
	</div>

	<div class="form-group"><label for="email" class="control-label">Email</label><input type="email" name="email" id="email" placeholder="Email" autofocus class="form-control"></div>
	<div class="form-group"><label for="password" class="control-label">Password</label><input type="password" name="password" id="password" placeholder="Password" class="form-control"></div>
	<div class="form-group"><button type="submit" class="btn btn-primary"><i class="fa fa-user"></i>Login</button><a href="/forgot" class="btn btn-link">Forgot your password?</a></div>
	<hr>
	<p>Sign in using OAuth</p>
	<a href="/auth/facebook" target="_top" class="btn btn-info btn-facebook btn-outline"><i class="fa fa-facebook"></i>Sign in with Facebook</a>
	<a href="/auth/twitter" class="btn btn-info btn-twitter btn-outline"><i class="fa fa-twitter"></i>Sign in with Twitter</a>
	<a href="/auth/google" class="btn btn-info btn-google-plus btn-outline"><i class="fa fa-google-plus"></i>Sign in with Google</a>
	<a href="/auth/github" class="btn btn-info btn-github btn-outline"><i class="fa fa-github"></i>Sign in with GitHub</a>
	<a href="/auth/linkedin" class="btn btn-info btn-linkedin btn-outline"><i class="fa fa-linkedin"></i>Sign in with LinkedIn</a>
	<a href="/auth/instagram" class="btn btn-info btn-instagram btn-outline"><i class="fa fa-instagram"></i>Sign in with Instagram</a>
</div>
