<div class="container">
	<div class="col-sm-8 col-sm-offset-2">
		<div class="page-header">
			<h3>Sign in</h3>
		</div>

		<div class="alert alert-danger" role="alert" ng-show="loginError">Invalid email or password</div>

		<form ng-submit="login()">
			<div class="form-group">
				<label for="email" class="control-label">Email</label>
				<input type="email" name="email" id="email" placeholder="Email" autofocus class="form-control" ng-model="email">
			</div>
			<div class="form-group">
				<label for="password" class="control-label">Password</label>
				<input type="password" name="password" id="password" placeholder="Password" class="form-control" ng-model="password">
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary"><i class="fa fa-user"></i>Login</button><a href="/forgot-password" class="btn btn-link">Forgot your password?</a>
			</div>
		</form>

		<hr>
		<p>Sign in using</p>
		<div class="oauth-login">
			<a href="/auth/facebook" target="_top" class="btn btn-default btn-facebook btn-sm"><i class="fa fa-facebook"></i>Facebook</a>
			<a href="/auth/twitter" target="_top" class="btn btn-default btn-twitter btn-sm"><i class="fa fa-twitter"></i>Twitter</a>
			<a href="/auth/google" target="_top" class="btn btn-default btn-google btn-sm"><i class="fa fa-google-plus"></i>Google</a>
			<a href="/auth/github" target="_top" class="btn btn-default btn-github btn-sm"><i class="fa fa-github"></i>GitHub</a>
			<a href="/auth/linkedin" target="_top" class="btn btn-default btn-linkedin btn-sm"><i class="fa fa-linkedin"></i>LinkedIn</a>
			<a href="/auth/instagram" target="_top" class="btn btn-default btn-instagram btn-sm"><i class="fa fa-instagram"></i>Instagram</a>
		</div>
	</div>
</div>
