<div class="container">
	<div class="col-sm-8 col-sm-offset-2">
		<div class="page-header">
			<h3>Create a New Password</h3>
		</div>

		<div class="alert alert-danger" role="alert" ng-show="resetError">Invalid link or password</div>
		<div class="alert alert-success" role="alert" ng-show="resetComplete">Successfully reset your password</div>

		<form ng-submit="reset()" ng-hide="resetComplete">
			<div class="form-group">
				<label for="password" class="control-label">New Password</label>
				<input type="password" name="password" id="password" placeholder="Password" class="form-control" ng-model="password">
			</div>
			<div class="form-group">
				<label for="confirmPassword" class="control-label">Confirm Password</label>
				<input type="password" name="confirmPassword" id="confirmPassword" placeholder="Confirm Password" class="form-control" ng-model="confirm">
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-success"><i class="fa fa-user-key"></i>Reset Password</button>
			</div>
		</form>
	</div>
</div>
